source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Exclude problematic CocoaPods versions that cause build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'xcodeproj', '< 1.26.0'
# concurrent-ruby >= 1.3.5 dropped its logger dependency, which breaks CocoaPods'
# activesupport chain with "uninitialized constant Logger" unless logger is required explicitly.
gem 'logger'
gem 'concurrent-ruby', '>= 1.3.7'
