/**
 * Jest Setup File
 * Mocks React Native modules for unit testing
 */

// Mock constants that would come from native modules
export const mockConstants = {
    logLevelDebug: 0,
    logLevelInfo: 1,
    logLevelWarn: 2,
    logLevelError: 3,
    productResultPurchased: 0,
    productResultCancelled: 1,
    productResultRestored: 2,
    sourceAppStore: 0,
    sourcePlayStore: 1,
    sourceHuaweiAppGallery: 2,
    sourceAmazonAppstore: 3,
    sourceNone: 4,
    firebaseAppInstanceId: 0,
    airshipChannelId: 1,
    airshipUserId: 2,
    batchInstallationId: 3,
    adjustId: 4,
    appsflyerId: 5,
    onesignalPlayerId: 6,
    mixpanelDistinctId: 7,
    clevertapId: 8,
    sendinblueUserEmail: 9,
    iterableUserId: 10,
    iterableUserEmail: 11,
    atInternetIdClient: 12,
    amplitudeUserId: 13,
    amplitudeDeviceId: 14,
    mparticleUserId: 15,
    customerIoUserId: 16,
    customerIoUserEmail: 17,
    branchUserDeveloperIdentity: 18,
    moEngageUniqueId: 19,
    batchCustomUserId: 20,
    consumable: 0,
    nonConsumable: 1,
    autoRenewingSubscription: 2,
    nonRenewingSubscription: 3,
    unknown: 4,
    runningModeTransactionOnly: 0,
    runningModeObserver: 1,
    runningModePaywallObserver: 2,
    runningModeFull: 3,
    presentationTypeNormal: 0,
    presentationTypeFallback: 1,
    presentationTypeDeactivated: 2,
    presentationTypeClient: 3,
    themeLight: 0,
    themeDark: 1,
    themeSystem: 2,
    userAttributeSourcePurchasely: 0,
    userAttributeSourceClient: 1,
    userAttributeString: 0,
    userAttributeBoolean: 1,
    userAttributeInt: 2,
    userAttributeFloat: 3,
    userAttributeDate: 4,
    userAttributeStringArray: 5,
    userAttributeIntArray: 6,
    userAttributeFloatArray: 7,
    userAttributeBooleanArray: 8,
}

// Create mock functions for all native methods
export const createMockPurchaselyModule = () => ({
    getConstants: jest.fn(() => mockConstants),
    start: jest.fn().mockResolvedValue(true),
    close: jest.fn(),
    userLogin: jest.fn().mockResolvedValue(true),
    userLogout: jest.fn(),
    isAnonymous: jest.fn().mockResolvedValue(false),
    getAnonymousUserId: jest.fn().mockResolvedValue('anonymous-user-id'),
    setLogLevel: jest.fn(),
    readyToOpenDeeplink: jest.fn(),
    setAttribute: jest.fn(),
    setLanguage: jest.fn(),
    synchronize: jest.fn(),
    fetchPresentation: jest.fn().mockResolvedValue({
        id: 'presentation-id',
        placementId: 'placement-id',
        type: 0,
        plans: [],
        metadata: {},
        height: null,
    }),
    presentPresentation: jest.fn().mockResolvedValue({
        result: 0,
        plan: null,
    }),
    presentPresentationWithIdentifier: jest.fn().mockResolvedValue({
        result: 0,
        plan: null,
    }),
    presentPresentationForPlacement: jest.fn().mockResolvedValue({
        result: 0,
        plan: null,
    }),
    presentProductWithIdentifier: jest.fn().mockResolvedValue({
        result: 0,
        plan: null,
    }),
    presentPlanWithIdentifier: jest.fn().mockResolvedValue({
        result: 0,
        plan: null,
    }),
    closePresentation: jest.fn(),
    hidePresentation: jest.fn(),
    showPresentation: jest.fn(),
    presentSubscriptions: jest.fn(),
    purchaseWithPlanVendorId: jest.fn().mockResolvedValue({
        vendorId: 'plan-id',
        productId: 'product-id',
        name: 'Test Plan',
    }),
    signPromotionalOffer: jest.fn().mockResolvedValue({
        planVendorId: 'plan-id',
        identifier: 'offer-id',
        signature: 'signature',
        nonce: 'nonce',
        keyIdentifier: 'key-id',
        timestamp: Date.now(),
    }),
    allProducts: jest.fn().mockResolvedValue([]),
    productWithIdentifier: jest.fn().mockResolvedValue({
        name: 'Test Product',
        vendorId: 'product-id',
        plans: [],
    }),
    planWithIdentifier: jest.fn().mockResolvedValue({
        vendorId: 'plan-id',
        productId: 'product-id',
        name: 'Test Plan',
    }),
    restoreAllProducts: jest.fn().mockResolvedValue(true),
    silentRestoreAllProducts: jest.fn().mockResolvedValue(true),
    userSubscriptions: jest.fn().mockResolvedValue([]),
    userSubscriptionsHistory: jest.fn().mockResolvedValue([]),
    isDeeplinkHandled: jest.fn().mockResolvedValue(false),
    isEligibleForIntroOffer: jest.fn().mockResolvedValue(true),
    setUserAttributeWithString: jest.fn(),
    setUserAttributeWithNumber: jest.fn(),
    setUserAttributeWithBoolean: jest.fn(),
    setUserAttributeWithDate: jest.fn(),
    setUserAttributeWithStringArray: jest.fn(),
    setUserAttributeWithNumberArray: jest.fn(),
    setUserAttributeWithBooleanArray: jest.fn(),
    incrementUserAttribute: jest.fn(),
    decrementUserAttribute: jest.fn(),
    userAttributes: jest.fn().mockResolvedValue({}),
    userAttribute: jest.fn().mockResolvedValue(null),
    clearUserAttribute: jest.fn(),
    clearUserAttributes: jest.fn(),
    clearBuiltInAttributes: jest.fn(),
    setDefaultPresentationResultHandler: jest.fn().mockResolvedValue({
        result: 0,
        plan: null,
    }),
    setPaywallActionInterceptor: jest.fn().mockResolvedValue({
        info: {},
        action: 'close',
        parameters: {},
    }),
    onProcessAction: jest.fn(),
    clientPresentationDisplayed: jest.fn(),
    clientPresentationClosed: jest.fn(),
    userDidConsumeSubscriptionContent: jest.fn(),
    setThemeMode: jest.fn(),
    setDynamicOffering: jest.fn().mockResolvedValue(true),
    getDynamicOfferings: jest.fn().mockResolvedValue([]),
    removeDynamicOffering: jest.fn(),
    clearDynamicOfferings: jest.fn(),
    revokeDataProcessingConsent: jest.fn(),
    setDebugMode: jest.fn(),
    addListener: jest.fn(),
    removeListeners: jest.fn(),
})

export const createMockPurchaselyViewModule = () => ({
    onPresentationClosed: jest.fn().mockResolvedValue({
        result: 0,
        plan: null,
    }),
})

// Setup NativeEventEmitter mock
export const mockEventEmitter = {
    addListener: jest.fn(() => ({ remove: jest.fn() })),
    removeAllListeners: jest.fn(),
    removeSubscription: jest.fn(),
    emit: jest.fn(),
    listenerCount: jest.fn(() => 0),
}
